# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-conn'
    subscriptionId: '1f6ffc81-0fc7-42fd-9aa0-303a7bf4cf4f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMPipeline-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/manmohanbatra/ARMPipeline-repo/refs/heads/main/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName ARMPipelineProj'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
